version: "3"

services:
  web:
    build: ./web
    command: python app.py
    volumes:
      - ./web/src:/code
    ports:
      - "5000:5000"
  # mqtt:
    # build: ./mqtt
    # volumes:
      # - ./mqtt/mosquitto/config:/mosquitto/config
    # ports:
      # - "1883:1883"
